# Generated by Django 5.2.5 on 2025-09-03 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_on_hand', models.IntegerField(default=0)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('qty', models.IntegerField(help_text='+ for in, - for out')),
                ('reason', models.CharField(choices=[('OPENING', 'Opening Balance'), ('PURCHASE', 'Purchase In'), ('SALE', 'Sale Out'), ('RETURN', 'Sales Return In'), ('ADJUST', 'Adjustment')], max_length=10)),
                ('reference', models.CharField(blank=True, help_text='Invoice or note no.', max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
            ],
            options={
                'ordering': ['-datetime'],
            },
        ),
    ]
